SERVER_NAME = 'Xqueue1'
SERVER_DESC = 'Xqueue for pyxserver'

HEADER_TAG = 'xqueue_header'

RABBIT_HOST = 'localhost'
RABBIT_QUEUE_NAME = 'xqueue'

# These are my 'pyxserver*' instances on AWS
#	to be dynamically generated by calling boto
WORKER_URLS = ['http://ec2-23-22-249-224.compute-1.amazonaws.com',
			   'http://ec2-50-16-41-236.compute-1.amazonaws.com',
			  ]
